import { Roboto_Slab, Mulish } from "next/font/google";
import "./globals.css";
import Link from "next/link";
// import Navbar from "../components/Home/Navbar"


const roboto_Slab = Roboto_Slab({
  subsets: ["latin"],
  variable: "--font-heading",
  display: "swap",
});
const mulish = Mulish({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

export const metadata = {
  title: "Mentrix",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${mulish.variable} ${roboto_Slab.variable}`}>
      <body >
        {/* <Navbar/> */}
        {children}
      </body>
    </html>
  );
}
