import { Roboto_Slab, Mulish } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner'
import { ViewTransitions } from 'next-view-transitions'

const roboto_Slab = Roboto_Slab({
  subsets: ["latin"],
  variable: "--font-heading",
  display: "swap",
});
const mulish = Mulish({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

export const metadata = {
  title: "Mentrix",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <ViewTransitions>
    <html lang="en" className={`${mulish.variable} ${roboto_Slab.variable}`}>
      <body >
        
          <Toaster position="top-center" richColors duration={3000} className="font-mono" toastOptions={{className: "text-base"}}/>
        {children}
        
      </body>
    </html>
    </ViewTransitions>
  );
}
